version: '3'
services:
  app:
    image: project2:latest
    container_name: family_tree
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_HOST=db
    command: npm run server
    ports:
      - '2222:2222'
    volumes:
      - ./:/app
  db:
    image: postgres:latest
    container_name: family_tree_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: project2
      POSTGRES_DB: family_tree_dev
    ports:
      - '5432:5432'
